# build is either 37 or 38
build: '37'

# these will be subdirectories in your working directory
plink2_cohorts: ['EXAMPLE_COHORT']

# Chromosome-separated plink files - they don't have to be 1.9 because the workflow does some QC
plink_prefix: '/project/ritchie/datasets/eMERGE/eMERGE_III_Imputed_UW/V2_wHarvard/eMERGE_Info_QC/subset.'
plink_flag: '--bfile'
plink_extensions: ['.bed', '.bim', '.fam']

# Plink QC parameters
# if not using any parameters, change plink_maf and plink_hwe to 0 and plink_geno and plink_mind to 1
plink_maf: 0.01
plink_geno: 0.01 
plink_mind: 0.05
plink_hwe: 1E-2

# These are column names from your phenotype and covariate files
plink_covars: ['AGE', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6']
plink_bin_phenos: ['T2D']
plink_quant_phenos: ['BMI']

sex_strat_cohorts: []

plink_chromosomes: ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22']
