repos:
  - repo: https://github.com/hritvikgupta/verma-lab-testing.git
    rev: main  # or specify a specific tag or commit hash
    hooks:
      - id: clean-config-files
        name: Clean Files Using testing Repo Hook
        entry: bash -c "curl -s https://raw.githubusercontent.com/hritvikgupta/verma-lab-testing/main/clean_paths_files.py | python3 - 'PMBB' '/project/' 'home/user' 'something' --directories='src,Plink_2.0_GWAS,PLINK'"
        language: system
        stages: [commit]
  
