repos:
  - repo: https://github.com/hritvikgupta/verma-lab-testing.git
    rev: main  # or specify a specific tag or commit hash
    hooks:
      - id: clean-config-files
        name: Clean Files Using testing Repo Hook
        entry: bash -c "curl -s https://raw.githubusercontent.com/hritvikgupta/verma-lab-testing/main/clean_paths_files.py?token=GHSAT0AAAAAACVILF764XNAL4DB656BV6I2ZVWIJ5A | python3 - PMBB"
        language: system
        stages: [commit]
